version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - DB_URL=jdbc:postgresql://db:5432/mydb
      - DB_USERNAME=user
      - DB_PASSWORD=password
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "3000:4173"
    environment:
      - VITE_API_ROOT=http://localhost:8080
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"